#pragma once
#include "Order.h"
#include "Trade.h"
#include <map>
#include <list>
#include <unordered_map>
#include <memory>
#include <vector>
#include <functional> // std::greater

class OrderBook {
public:
    // addOrder takes OWNERSHIP of the order (unique_ptr passed by value,
    // "moved" in) - once you call this, the OrderBook owns that memory, not
    // you. It returns every Trade generated by matching this order against
    // the book. If the order (a LimitOrder) isn't fully filled, the
    // remainder starts resting in the book automatically.
    std::vector<Trade> addOrder(std::unique_ptr<Order> order);

    // Cancels a resting order by id. Returns false if it's not found
    // (already filled, already cancelled, or never existed) - the caller
    // MUST check this, we don't silently ignore a bad cancel request.
    bool cancelOrder(OrderId id);

    // "Top of book" - the single best price on each side, if one exists.
    // We'll implement these using std::optional-style sentinel checks.
    bool getBestBid(double& outPrice) const;
    bool getBestAsk(double& outPrice) const;

    void printBook() const; // debug helper, prints the ladder

private:
    // WHY std::map, not std::unordered_map, for the price levels:
    // we need the price levels SORTED (best price = one end of iteration),
    // which unordered_map cannot give us. std::map is a balanced binary
    // search tree (red-black tree) - O(log n) insert/erase/find, and
    // begin()/rbegin() always give the smallest/largest key in O(1).
    //
    // WHY std::list, not std::vector, INSIDE each price level:
    // orders at the same price must preserve arrival order (time priority),
    // and we frequently need to erase from the MIDDLE of this list (an
    // order gets cancelled or fully filled, possibly not at the front).
    // std::list gives O(1) erase given an iterator, and - crucially -
    // erasing or inserting elsewhere in a list does NOT invalidate other
    // iterators into it (unlike std::vector, where erasing shifts everything
    // after it and invalidates iterators/pointers past that point). We rely
    // on that stability below for orderLocation_.

    // Bids: sorted so the HIGHEST price is "first" -> use std::greater<double>
    // as the comparator instead of the default std::less<double>.
    std::map<double, std::list<Order*>, std::greater<double>> bids_;

    // Asks: default std::less<double> -> LOWEST price is naturally "first".
    std::map<double, std::list<Order*>> asks_;

    // Who actually OWNS the Order objects. The lists above store raw,
    // NON-OWNING Order* pointers into these unique_ptrs - this is safe
    // specifically because std::unordered_map guarantees that erasing one
    // element never invalidates pointers/references to OTHER elements
    // (only iterators to the erased element itself become invalid). So a
    // raw Order* handed out from here stays valid until that exact order's
    // entry is erased - which we only do once, when the order is fully
    // done (filled or cancelled).
    std::unordered_map<OrderId, std::unique_ptr<Order>> ownedOrders_;

    // To cancel or fill an order fast, we need to know exactly WHERE it
    // lives: which side, which price level, and which list iterator. Without
    // this index, cancelling order #4821 would mean scanning every price
    // level on both sides - O(n). With it, cancellation is O(log n)
    // (map lookup by price) instead of O(n).
    struct OrderLocation {
        Side side;
        double price;
        std::list<Order*>::iterator iterator;
    };
    std::unordered_map<OrderId, OrderLocation> orderLocation_;

    // --- internal helpers, implemented in the .cpp ---
    std::vector<Trade> matchIncoming(Order* incoming);
    void restInBook(Order* incoming); // add a still-open LIMIT order to the book
    void removeFromLevel(OrderId id); // erase bookkeeping for a filled/cancelled order
};
